import { MigrationInterface, QueryRunner } from "typeorm";

export class Init1779107820982 implements MigrationInterface {
    name = 'Init1779107820982'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP FOREIGN KEY \`FK_0b0fc32fe6bd0119e281628df7a\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP FOREIGN KEY \`FK_64cd97487c5c42806458ab5520c\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_ad074b0f95ff0488162868be2c7\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_bae04782e4d2b4d4c978528970c\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`FK_4a08d003e00caf075a4a212d23d\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`FK_8e1215206acb19f1c38dbda9091\``);
        await queryRunner.query(`DROP INDEX \`IDX_ad074b0f95ff0488162868be2c\` ON \`role_permissions\``);
        await queryRunner.query(`DROP INDEX \`IDX_bae04782e4d2b4d4c978528970\` ON \`role_permissions\``);
        await queryRunner.query(`DROP INDEX \`IDX_4a08d003e00caf075a4a212d23\` ON \`user_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_8e1215206acb19f1c38dbda909\` ON \`user_roles\``);
        await queryRunner.query(`ALTER TABLE \`permissions\` DROP COLUMN \`create_time\``);
        await queryRunner.query(`ALTER TABLE \`permissions\` DROP COLUMN \`update_time\``);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`create_time\``);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`update_time\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`nick_name\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`head_pic\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`phone_number\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`is_frozen\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`is_admin\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`create_time\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`update_time\``);
        await queryRunner.query(`ALTER TABLE \`meeting_rooms\` DROP COLUMN \`is_booked\``);
        await queryRunner.query(`ALTER TABLE \`meeting_rooms\` DROP COLUMN \`create_time\``);
        await queryRunner.query(`ALTER TABLE \`meeting_rooms\` DROP COLUMN \`update_time\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP COLUMN \`start_time\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP COLUMN \`end_time\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP COLUMN \`create_time\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP COLUMN \`update_time\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP COLUMN \`room_id\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD PRIMARY KEY (\`permissions_id\`)`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP COLUMN \`roles_id\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP COLUMN \`permissions_id\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD PRIMARY KEY (\`roles_id\`)`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP COLUMN \`users_id\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP COLUMN \`roles_id\``);
        await queryRunner.query(`ALTER TABLE \`permissions\` ADD \`createTime\` datetime(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`permissions\` ADD \`updateTime\` datetime(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`createTime\` datetime(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`updateTime\` datetime(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`nickName\` varchar(50) NOT NULL COMMENT '昵称'`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`headPic\` varchar(100) NULL COMMENT '头像'`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`phoneNumber\` varchar(20) NULL COMMENT '手机号'`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`isFrozen\` tinyint NOT NULL COMMENT '是否冻结' DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`isAdmin\` tinyint NOT NULL COMMENT '是否管理员' DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`createTime\` datetime(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updateTime\` datetime(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`meeting_rooms\` ADD \`isBooked\` tinyint NULL COMMENT '会议室是否被预订' DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`meeting_rooms\` ADD \`createTime\` datetime(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`meeting_rooms\` ADD \`updateTime\` datetime(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD \`startTime\` datetime NOT NULL COMMENT '预订开始时间'`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD \`endTime\` datetime NOT NULL COMMENT '预订结束时间'`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD \`createTime\` datetime(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD \`updateTime\` datetime(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD \`userId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD \`roomId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD \`rolesId\` int NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD \`permissionsId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD PRIMARY KEY (\`rolesId\`, \`permissionsId\`)`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD \`usersId\` int NOT NULL PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD \`rolesId\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD PRIMARY KEY (\`usersId\`, \`rolesId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_0cb93c5877d37e954e2aa59e52\` ON \`role_permissions\` (\`rolesId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_d422dabc78ff74a8dab6583da0\` ON \`role_permissions\` (\`permissionsId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_99b019339f52c63ae615358738\` ON \`user_roles\` (\`usersId\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_13380e7efec83468d73fc37938\` ON \`user_roles\` (\`rolesId\`)`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD CONSTRAINT \`FK_38a69a58a323647f2e75eb994de\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD CONSTRAINT \`FK_0172b36e4e054d6ebb819d58efb\` FOREIGN KEY (\`roomId\`) REFERENCES \`meeting_rooms\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_0cb93c5877d37e954e2aa59e52c\` FOREIGN KEY (\`rolesId\`) REFERENCES \`roles\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_d422dabc78ff74a8dab6583da02\` FOREIGN KEY (\`permissionsId\`) REFERENCES \`permissions\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`FK_99b019339f52c63ae6153587380\` FOREIGN KEY (\`usersId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`FK_13380e7efec83468d73fc37938e\` FOREIGN KEY (\`rolesId\`) REFERENCES \`roles\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`FK_13380e7efec83468d73fc37938e\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`FK_99b019339f52c63ae6153587380\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_d422dabc78ff74a8dab6583da02\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_0cb93c5877d37e954e2aa59e52c\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP FOREIGN KEY \`FK_0172b36e4e054d6ebb819d58efb\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP FOREIGN KEY \`FK_38a69a58a323647f2e75eb994de\``);
        await queryRunner.query(`DROP INDEX \`IDX_13380e7efec83468d73fc37938\` ON \`user_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_99b019339f52c63ae615358738\` ON \`user_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_d422dabc78ff74a8dab6583da0\` ON \`role_permissions\``);
        await queryRunner.query(`DROP INDEX \`IDX_0cb93c5877d37e954e2aa59e52\` ON \`role_permissions\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD PRIMARY KEY (\`usersId\`)`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP COLUMN \`rolesId\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP COLUMN \`usersId\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD PRIMARY KEY (\`rolesId\`)`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP COLUMN \`permissionsId\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP COLUMN \`rolesId\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP COLUMN \`roomId\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP COLUMN \`userId\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP COLUMN \`updateTime\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP COLUMN \`createTime\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP COLUMN \`endTime\``);
        await queryRunner.query(`ALTER TABLE \`bookings\` DROP COLUMN \`startTime\``);
        await queryRunner.query(`ALTER TABLE \`meeting_rooms\` DROP COLUMN \`updateTime\``);
        await queryRunner.query(`ALTER TABLE \`meeting_rooms\` DROP COLUMN \`createTime\``);
        await queryRunner.query(`ALTER TABLE \`meeting_rooms\` DROP COLUMN \`isBooked\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updateTime\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`createTime\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`isAdmin\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`isFrozen\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`phoneNumber\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`headPic\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`nickName\``);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`updateTime\``);
        await queryRunner.query(`ALTER TABLE \`roles\` DROP COLUMN \`createTime\``);
        await queryRunner.query(`ALTER TABLE \`permissions\` DROP COLUMN \`updateTime\``);
        await queryRunner.query(`ALTER TABLE \`permissions\` DROP COLUMN \`createTime\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD \`roles_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD PRIMARY KEY (\`roles_id\`)`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD \`users_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD PRIMARY KEY (\`users_id\`, \`roles_id\`)`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD \`permissions_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD PRIMARY KEY (\`permissions_id\`)`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD \`roles_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD PRIMARY KEY (\`roles_id\`, \`permissions_id\`)`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD \`room_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD \`user_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD \`update_time\` datetime(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD \`create_time\` datetime(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD \`end_time\` datetime NOT NULL COMMENT '预订结束时间'`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD \`start_time\` datetime NOT NULL COMMENT '预订开始时间'`);
        await queryRunner.query(`ALTER TABLE \`meeting_rooms\` ADD \`update_time\` datetime(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`meeting_rooms\` ADD \`create_time\` datetime(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`meeting_rooms\` ADD \`is_booked\` tinyint NULL COMMENT '会议室是否被预订' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`update_time\` datetime(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`create_time\` datetime(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`is_admin\` tinyint NOT NULL COMMENT '是否管理员' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`is_frozen\` tinyint NOT NULL COMMENT '是否冻结' DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`phone_number\` varchar(20) NULL COMMENT '手机号'`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`head_pic\` varchar(100) NULL COMMENT '头像'`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`nick_name\` varchar(50) NOT NULL COMMENT '昵称'`);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`update_time\` datetime(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`roles\` ADD \`create_time\` datetime(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`permissions\` ADD \`update_time\` datetime(6) NOT NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`permissions\` ADD \`create_time\` datetime(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`CREATE INDEX \`IDX_8e1215206acb19f1c38dbda909\` ON \`user_roles\` (\`users_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_4a08d003e00caf075a4a212d23\` ON \`user_roles\` (\`roles_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_bae04782e4d2b4d4c978528970\` ON \`role_permissions\` (\`permissions_id\`)`);
        await queryRunner.query(`CREATE INDEX \`IDX_ad074b0f95ff0488162868be2c\` ON \`role_permissions\` (\`roles_id\`)`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`FK_8e1215206acb19f1c38dbda9091\` FOREIGN KEY (\`users_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`FK_4a08d003e00caf075a4a212d23d\` FOREIGN KEY (\`roles_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_bae04782e4d2b4d4c978528970c\` FOREIGN KEY (\`permissions_id\`) REFERENCES \`permissions\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_ad074b0f95ff0488162868be2c7\` FOREIGN KEY (\`roles_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD CONSTRAINT \`FK_64cd97487c5c42806458ab5520c\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`bookings\` ADD CONSTRAINT \`FK_0b0fc32fe6bd0119e281628df7a\` FOREIGN KEY (\`room_id\`) REFERENCES \`meeting_rooms\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
